### ISSUE TITLE
[tracker] next step Kubeflow website model registry section

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#109]
- [x] add additional diagrams to address [this comment](https://github.com/kubeflow/website/pull/3698#issuecomment-2069810560) and [this comment](https://github.com/kubeflow/website/pull/3698#discussion_r1597274742)
  - this is being done with https://github.com/kubeflow/website/pull/3828 
- [x] https://github.com/kubeflow/website/pull/3740
  - [x] expand on section "installation" to document how to install MR separately from KF ([comment](https://github.com/kubeflow/website/pull/3698#discussion_r1597273996))
  - [x] avoid ref to main and use tag ([comment](https://github.com/kubeflow/website/pull/3698#discussion_r1608544930)) for installation
  - [x] add OWNER file in `content/en/docs/components/model-registry` (can take [katib file as example]
- [x] add example instructions for dry-run REST API inside of notebook
this is being done with https://github.com/kubeflow/website/pull/3788
- [x] consider for "registered model" version in kserve part of tutorial to be consistent or similar to the one from previous steps
this is being done with https://github.com/kubeflow/website/pull/3788
- [x] request if it's possible to add (while Alpha, with "alpha" label, with `*` postfix, ...) a "Model Registry (alpha)" in the KF architecture diagram
  - this is being done by Andrey here: https://github.com/kubeflow/website/pull/3780

**Comment by tarilabs** [comment]
> add additional diagrams to address [this comment](https://github.com/kubeflow/website/pull/3698#issuecomment-2069810560) and [this comment](https://github.com/kubeflow/website/pull/3698#discussion_r1597274742)
> * this is being done with [model registry: update MLOps diagrams website#3828](https://github.com/kubeflow/website/pull/3828)

last item completed on Aug 7th.
