### ISSUE TITLE
[Kubeflow 1.10] Define Kubeflow 1.10 Roadmap for Model Registry

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#175]
🚧  this roadmap is being discussed in the [biweekly Model Registry meeting](https://www.kubeflow.org/docs/about/community/#kubeflow-community-calendars) and might be subject to change 🏗️  join us in the meeting or on [Model Registry Slack channel](https://www.kubeflow.org/docs/about/community/#slack-channels:~:text=Model%20Registry,kubeflow%2Dmodel%2Dregistry) for your feedback!
_As suggested by KF Release team, as the KF 1.10 will kick-start, anything which won't be attainable for the 1.10 plan, will carry-over to a "Roadmap for KF 1.Next" roadmap (thanks @rimolive for the suggestion!)_

- [x] Kubeflow Model Registry UI (ref: @ederign)
_The first version of the Kubeflow Model Registry web app will include features like model registration and listing, detailed model views with metadata, version listings, and the ability to archive models on multiple model registries._
(see [here for details](https://github.com/kubeflow/model-registry/issues/175#issuecomment-2400485559))
- Improve the project, CNCF maturity, etc.
  - [ ] Multi-arch images - for the Go REST server specifically
  - [x] #327
  - [x] #323
- [x] MLMD-related enhancements (now unplanned https://github.com/kubeflow/model-registry/issues/865)
examples:
  - [ ] multi-tenancy https://github.com/kubeflow/model-registry/issues/120
  - [ ] single instance with KFP(?)
  etc.
- [x] "shift-left" testing - incorporating CI testing we have Midstream, to Upstream  (ref: @tonyxrmdavidson)
- [x] Integration/Import from other Registries - e.g.: integration of MLFlow (ref: https://github.com/kubeflow/model-registry/issues/94 now https://github.com/kubeflow/model-registry/issues/1225)
- Improve integration with other KF components
  - [ ] e.g.: harden CSI blueprint (@lampajr)
  - [ ] integration blueprints with Katib/HPO:
  [example](https://github.com/kubeflow/katib/issues/2306#issuecomment-2050130668)
  - [ ] keep tabs with Feast integrations ( https://github.com/feast-dev/feast/issues/4258 @franciscojavierarceo )
  - [ ] integration/blueprint with Training Operator (see [here](https://github.com/kubeflow/training-operator/issues/2101#issuecomment-2097204327))
  - [ ] and other blueprints (for [example](https://github.com/kubeflow/model-registry/issues/130))
- [x] Integration Storage solutions for Model Registry, with OCI being the preferred option (ref: @tarilabs)
- [ ] Carry-over [from 1.9](https://github.com/kubeflow/model-registry/issues/3):
  - [x] brief docs on Manifest quickstart, pointers to "read more on how you can further kustomize"
  - [ ] confirm if any special requirements for Istio/Cert-manager

---

References for KF 1.10 from Release team or other:
- dependency matrix https://github.com/kubeflow/community/issues/767

**Comment by franciscojavierarceo** [comment]
Linking the ticket in the Feast repo https://github.com/feast-dev/feast/issues/4258

**Comment by ederign** [comment]
@tarilabs, we are happy to provide an update regarding the Kubeflow Model Registry web app for the 1.10 scope.


----
#### Kubeflow Model Registry UI
The first version of the Kubeflow Model Registry web app will include features like model registration and listing, detailed model views with metadata, version listings, and the ability to archive models on multiple model registries.

----

We still need to investigate and discuss how to integrate our work with the central dashboard regarding iframe integration, security (logged user), auth, and topology deployment. We will keep everyone posted as you progress on those.

**Comment by tarilabs** [comment]
Thank you for sharing awesome news with the community @ederign and team

**Comment by tarilabs** [comment]
there was a suggestion from Valentina in biweekly to update this roadmap and roll-over items which likely not land for 1.10.

**Comment by varodrig** [comment]
Issue needs to be updated reflecting what will be part of Release 1.10

**Comment by milosjava** [comment]
we have a MR call after the release so I can update that offline

**Comment by tarilabs** [comment]
closing with https://blog.kubeflow.org/kubeflow-1.10-release/
