### ISSUE TITLE
[Kubeflow 1.9] Define Kubeflow 1.9 Roadmap for Model Registry

### ISSUE THREAD

**Issue by rareddy** [kubeflow/model-registry#3]
For Kubeflow 1.9 roadmap needs to be defined.

- [x] code "uplift"
  - Per the Model Registry [proposal document](https://github.com/kubeflow/community/pull/682), bring in the usage of the`ml-metadata` project as the initial repository to build a Model Registry.
  - Build an API Server for supporting the client tools/UI to interact with Model Registry.
  - https://github.com/kubeflow/model-registry/pull/6
- [x] Manifests to deploy the components of Model Registry into Kubernetes
  - [x] https://github.com/opendatahub-io/model-registry-bf4-kf/issues/269
  - [x] #35
- [ ] Istio service mesh configuration
  - [x] (generic) Istio config quickstart https://github.com/kubeflow/model-registry/tree/main/manifests/kustomize/options/istio
  - [ ] brief docs on Manifest quickstart, pointers to "read more on how you can further kustomize"
- [x] Publication of KF MR container images
  - https://github.com/kubeflow/model-registry/issues/23
  - we can use GH Action to "cut" a release Alpha image, when needed/requested
- [ ] confirm the following questions as testing completes:
  - [x] What version of Notebooks would you like to include for the 1.9 release?
  no specific version required, there is a MR Python client on PyPI: https://pypi.org/project/model-registry
  - [x] Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?
  this issue https://github.com/kubeflow/model-registry/issues/3
  - [ ] If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?
    - Knative (not used)
    - Istio (no specific version? we will check for tested version)
    - [x] Kubernetes (no specific version? we will check for tested version)
    #44 
    - Cert-Manager (no specific version? we will check for tested version)
    - [x] #42
    - [x] #90
- [x] https://github.com/kubeflow/website/pull/3698, to highlight:
  - “How to onboard users?”
  - Add to KF website sidebar
    - How to install
    - 0.x and Alpha -> unstable make “disclaimer” type of state
    - How to use it, like the Python client, highlight integrations with other components
- Sync with KF/manifest repo:
  - [x] in KF/manifest make sync script: https://github.com/kubeflow/manifests/pull/2682
  - [x] in this repo, ensure proper files per requirements: https://github.com/kubeflow/model-registry/pull/69
  - [x] in KF/manifest make functional testing: https://github.com/kubeflow/manifests/pull/2694
  incorporated into: https://github.com/kubeflow/manifests/pull/2697
  - [x] NetworkPolicies will be checked by Manifest-wg (KF community call 2024-04-25)
  tracked with https://github.com/kubeflow/manifests/issues/2701
  (not a blocker for KF1.9 release)

stretch goals:
  - https://github.com/kubeflow/model-registry/issues/24

## References

KF 1.9 version matrix tracker:
- https://github.com/kubeflow/manifests/issues/2613

**Comment by tarilabs** [comment]
drafting so far:

> What version of Notebooks would you like to include for the 1.9 release?

no specific version required, there is a MR Python client on PyPI: https://pypi.org/project/model-registry/

> Could you provide a branch/tag for this version? (note: It doesn't have to be final)

we will likely tag an alpha version, once ready from default branch (into specific branch if needed for branching-out).

> Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?

- we need to uplift odh repo here as upstream
- https://github.com/opendatahub-io/model-registry/issues/269
- service mesh
- OPTIONAL. https://github.com/opendatahub-io/model-registry/issues/262

> If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

Knative (not used)
Istio (need details)
Kubernetes (no specific version? we will check for tested version)
Cert-Manager (no specific version? we will check for tested version)
Kustomize (no specific version? we will check for tested version)

**Comment by tarilabs** [comment]
updated drafting so far:

> What version of Notebooks would you like to include for the 1.9 release?

no specific version required, there is a MR Python client on PyPI: https://pypi.org/project/model-registry/

> Could you provide a branch/tag for this version? (note: It doesn't have to be final)

we will likely tag an alpha version, once ready from default branch (into specific branch if needed for branching-out).

> Can you share a link to all open / work in progress issues that you're expecting to include in the 1.9?

- we need to uplift odh repo here as upstream: see https://github.com/kubeflow/model-registry/pull/6 or analogous being actioned on
- https://github.com/opendatahub-io/model-registry/issues/269
- service mesh (Note: look for Istio confirmation)
- OPTIONAL. https://github.com/opendatahub-io/model-registry/issues/262

> If you're using the following dependencies, could you provide the versions you'll be supporting for each dependency?

Knative (not used)
Istio (need details)
Kubernetes (no specific version? we will check for tested version)
Cert-Manager (no specific version? we will check for tested version)
Kustomize (no specific version? we will check for tested version)

maybe check the MR tests have gone through the KF1.9 supported versions?
KF 1.9 version matrix tracker:
- https://github.com/kubeflow/manifests/issues/2613

**Comment by StefanoFioravanzo** [comment]
@tarilabs  @rareddy Could we update the first comment of this issue with a checklist of items you want to address in this release? Since this is a new component, it would be very good to have an exec summary of what users can expect to experience with the first (alpha?) release.

**Comment by StefanoFioravanzo** [comment]
I would suggest creating a separate "Roadmap" issue outlining the high-level the roadmap throughout the next months and releases, since it seems like this was discussed extensively in meetings. Also, let's think about how we can onboard new users to the Model Registry once we release 1.9. Most importantly:

1. Documentation plan
2. Installation plan (As a Day 2 operation I guess)

**Comment by StefanoFioravanzo** [comment]
Hello @rareddy @tarilabs, this is a kind reminder that Monday, March 4th will be our Kubeflow 1.9 release development checkpoint, we will be halfway through our dev cycle, and we expect most of the work to be well underway (reminder: code freeze is scheduled for Apr 15th)

Can you please acknowledge your status with respect to your roadmap, comment on the progress made so far, and provide an assessment of the work that remains?

(understandably) Not everything may be completed in time. Please proactively let the release team know if there are delays, blockers, or uncertain situations, know so that we can align expectations and try and help you out, if possible.

Please, can you update the first comment in this issue with a check of tasks that need to be completed for a successful Model Registry alpha release? There are quite a few things being discussed in comments here and elsewhere (meeting notes etc.). Let's try and consolidate into a plain list of deliverables.

**Comment by tarilabs** [comment]
With MR part of KF 1.9: https://blog.kubeflow.org/kubeflow-1.9-release/#model-registry ,
resolving this tracker.

The next roadmap tracker can be found at:
- https://github.com/kubeflow/model-registry/issues/175
