### ISSUE TITLE
[tracker] next steps ModelRegistry Custom Storage Initializer

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#33]
- [x] Add image build directive in the model registry root Makefile (re-using csi Makefile)
- [x] update KServe website, following this: https://github.com/kserve/website/pull/346
to show integration of CSI image here in KF/model-registry instead of the current placeholder of the example`image: abc/model-registry-storage-initializer:latest` (should read eventually something like `image: kubeflow/model-registry-storage-initializer:latest`)
  - https://github.com/kserve/website/pull/414
- [x] Set container image registry
- [x] Add some testing focusing on the MR interaction using testcontainers (mocking the download itself)
- [x] add a simple, short "tutorial" on kubeflow.org website ( follow-up with @Al-Pragliola )

Stretch goals:
- [ ] Use `kiota` (or other openapi code-generators) to autogenerate the client, this will make the CSI _less_ dependent on the internal model registry implementation (this will also make the CSI just tied to the openapi spec rather than MR version)
  - https://github.com/kubeflow/model-registry/issues/338

See previous work on this topic:
- https://github.com/kubeflow/model-registry/pull/25#issuecomment-1973008080
- https://github.com/kubeflow/model-registry/issues/24

If you-reading-this-issue start to work on any of these points, kindly notify by creating a relevant issue, assign it to yourself and reach out to confirm scope with the maintainers :)

**Comment by tarilabs** [comment]
this is being worked with: https://github.com/kubeflow/model-registry/pull/154

**Comment by lampajr** [comment]
Stretch goal being tracked by https://github.com/kubeflow/model-registry/issues/338

@tarilabs I think that all non-stretch goals can be considered as done/completed so I think you can tick the coresponding boxes in this PR's description

**Comment by tarilabs** [comment]
/reopen

I believe all boxes are meant be ticked, to review.

**Comment by lampajr** [comment]
> I believe all boxes are meant be ticked, to review.

@tarilabs  I think the "Update KServe Website" can be ticked as well (this should have been addressed by your PR https://github.com/kserve/website/pull/414)

The only outstanding bullet point is "add a simple, short "tutorial" on kubeflow.org website ( follow-up with @Al-Pragliola )", but not sure whether this is kind of needed or not. Up to you guys.

**Comment by tarilabs** [comment]
> I believe all boxes are meant be ticked, to review.

thank you @lampajr @Al-Pragliola for confirming all boxes can be ticket.

**Comment by tarilabs** [comment]
marking as Complete.
